### ISSUE TITLE
No OCR on most of the documents

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#10]
For the documents Hostinsky1879, Kunkel1863, KargElerrt1931, and apparently most other documents, I see a completely empty transcription box, and no segmentation of page elements has been done yet.

As far as I can tell, only the following 5 texts have OCR available at the moment:

- Weitzmann 1861
- Weitzmann 1860
- Ideen zu einer "Lehre von..."
- Riemann 1880
- Die Natur der Harmonik

The pages in these documents also seem to be marked as "In Progress", while the ones without OCR are still "new".

What is going on here? I am asking since I was supposed to try a page in all files. Is it known when the OCR will be available for all of them?

**Comment by fabianmoss** [comment]
I think this is my fault. It seems I did not yet run the OCR on all documents. Thanks for bringing it to my attention. I'll post an update here once they are all done (might take a couple of hours).

**Comment by m-k94** [comment]
Okay! In the meantime I will do the ones with OCR ready.

**Comment by m-k94** [comment]
Now, the pages of said documents are shown as "in Progress", but yellow instead of green. Apparently, this means that they have a rough representation of the segmentation but no transcription yet!

**Comment by fabianmoss** [comment]
Yes, I think Transkribus marks each page as "In Progess" when there are any changes applied automatically. But you can always change the status per page manually.
