### ISSUE TITLE
Unicode triangle symbols in Transcribus

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#13]
On page 25 of Ideen zu einer "Lehre..., there are also two triangles, one pointing up, the other down. I wanted to simply use unicode symbols in the transcription, since they are inline and rather straightforward: △ ▽ 

However, when I paste these into Transcribus, I get triangles which point to left and right, instead of up and down.

So I guess my question is twofold:
1. Should we use unicode symbols in such situations?
2. If yes, how can I make sure they display as I intend them to?

**Comment by fabianmoss** [comment]
I believe that unicode characters would be a good solution. However, if Transkribus doesn't display them correctly, it is not helpful. It might still be that they are correct after export - it's unicode after all.
I think that it is a similar situation as in issue #4. So the solution would be the following:

1. transcribe it with the unicode characters as you suggest, even if they are displayed differently in Transkribus.
2. in the labeling/tagging stage, we will mark it up as a "special character" or something and replace it with the appropriate sign in a subsequent step

**Comment by m-k94** [comment]
Okay, that sounds like the best solution. I will add the tags as soon as the tag-transfer problem is fixed.
