### ISSUE TITLE
Editorial Rule for Using - for = in Fraktur? 

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#14]
Another small question concerning editorial rules:

Texts in Fraktur font often use double lines to connect words. These then get transcribed like "C dur=Dreiklang" in Weitzmann_1860. (p. 25, for example)

Should we keep these as double lines or replace them with a simple dash? (C dur-Dreiklang)

In my opinion, it's only a feature of the font and should therefore be replaced.

**Comment by fabianmoss** [comment]
Yes, in this case we modernize the transcription. Please add this also to the Editorial notes.

**Comment by fabianmoss** [comment]
(and close this issue)
