### ISSUE TITLE
Riemann's Ideen - segmentation and tagging of "- 4 -" type sub-headings

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#17]
Riemann structures his chapters using numbers, in the style of "- 4 -".

Oftentimes, they represent single paragraphs. As in the following example page (p. 5):

![image](https://user-images.githubusercontent.com/75686579/104135175-a5612280-538e-11eb-94cd-0d4d472cf99d.png)

We should decide what to do with these. Should they have their own text region, or be connected to the following one? 
And if they do represent independent text regions, are they "headings"? In a way, they do fulfill that function, but only at a very minor level. So far I have marked them as "float", since they break up the main text. But I am very unsure about that.

**Comment by fabianmoss** [comment]
I think they always mark paragraphs. In other sources, paragraphs are marked with "§x" but here it is just the number. There is a great variety in how these texts are structured internally and we have to come up with a good common system. For now, I suggest to include the numbers in the respective paragraphs. In another source (I don't remember which one), we had even named paragraphs like "1. Tonarten". I suggest to transcribe the numbers as a separate line but include them with the rest of the text in a paragraph.

**Comment by m-k94** [comment]
Okay, I will change it in accordance to your answer! 

Btw, I will add all of these things to the wiki later. I want to create a section with text-specific notes, including particularities of layout as well as frequent causes of errors in the OCR. But I'm collecting the information in a private document for now, until I'm a bit more sure about certain things.
