### ISSUE TITLE
Riemann Ideen - page turns within images?

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#18]
For a while, I was confused why I don't find page-numbers on every image. Meaning the little "SEITE: x" notes. 
But now, it has finally dawned on me that the "pages" of the document are actually slightly larger than the images. Starting from page 7 and 8, this actually starts to lead to some strange layout configurations: 

Page 7 has a large gap between a stray half-sentence on top of the page, and the continuing paragraph after the page-break indicated by the line:

![image](https://user-images.githubusercontent.com/75686579/104136091-59b17780-5394-11eb-9d7e-b94eebdf5711.png)
(p. 7)

and by the next page, the pagebreak is already close to the middle of the image.

![image](https://user-images.githubusercontent.com/75686579/104136058-2cfd6000-5394-11eb-9370-1b07612f9060.png)
(p. 8)

Is any of this a problem? I am not sure. But I do find it a little awkward that there are - taking in account the /² symbols from the other issue - basically three different kinds of "pages" in this text, all overlapping with differing sizes.

**Comment by fabianmoss** [comment]
This document is a mess unfortunately. If I can reconstruct it correctly it is as follows:

1. There is an original printed source, available in some libraries. 
2. This source has been transcribed and published in the Frankfurter Zeitschrift für Musikwissenschaft (an online journal that doesn't exist anymore), where you could browse through different HTML pages, corresponding to the "SEITE: X" notes.
3. A PDF export of this website lead to yet another pagination (the images in Transkribus).
4. So, we have actually three different pagination systems at work here. 
5. The only interesting one is that of the original source, indicated by the "/^x" tags.
