### ISSUE TITLE
Table on Hauptmann "Die Natur der Metrik...", p. 13

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#20]
On the page mentioned in the title of this issue, there is a simple illustration linking note-names to numbers.

![image](https://user-images.githubusercontent.com/75686579/104241341-ce9cb400-545d-11eb-955a-d2998cba15e4.png)

How should we tag, segment and transcribe this page element? 

I suppose one could also represent it as a "paragraph" with two lines, but it's semantically important that the corresponding elements are vertically aligned. For that reason, I marked it as a "table" in structural-metadata. However, now I cannot see how I can fill it out anymore... Is there a way to do have it be a table but also fill it out in Transkribus?

**Comment by fabianmoss** [comment]
That's a hard one but I imagine we will encounter several similar situations. It could be transcribed as a table but it lacks a table head with column names (which tables usually have). It could also be interpreted as a diagram. In any case, I agree that the vertical alignment is crucial here so having to normal paragraph lines is not a good solution. Please mark it up as an image/diagram. We will deal with the encoding later (and probably use LaTeX, like in the case of functional harmonic symbols).

**Comment by m-k94** [comment]
These tables also mess with the paragraph structure quite a bit. In the example above, it's sort of it's own paragraph, but on this page (15), it's technically part of the same paragraph as what comes before and after it:

![image](https://user-images.githubusercontent.com/75686579/104339817-4fa88980-54f8-11eb-9335-dc0a11f9b448.png)

It feels a bit weird to just mark the first line as a "paragraph", but I guess it's probably the right way? The alternative would be to have overlapping regions on top of one another, or to draw a complex shape around the diagram, keeping the paragraph text together.

**Comment by fabianmoss** [comment]
For this situation, there might be a solution. It is possible to link to shapes (such as paragraphs) to each other. See page 7/8 here: https://transkribus.eu/wiki/images/f/f7/How_to_Use_the_Structural_Tagging_Feature.pdf 
That could be a solution here but we would have to check what it looks like after exporting since in this situation it is absolutely crucial that the "table" is embedded in the paragraph.

Unfortunately, this is not possible to link shapes on different pages.

**Comment by m-k94** [comment]
Okay, interesting. I tried this feature. Not sure what it does exactly, though. As far as I understand, the paragraphs are still recognized as individual entities. Linking seems to be most relevant for footnotes, which I was also wondering about, so it's great that you pointed it out!

I experimented a little bit with this, different pages feature different solutions to the problem now:

**page 13:** separate paragraphs, reading-order adjusted
**page 14:** paragraphs merged around the table, using merge too <- this looks pretty good to me too. You can just mark paragraphs and merge them, even if there is something in between them. But it might mess up the reading order, actually, as the table is "read" after the paragraph.
**page 15:** paragraphs around the table, linked.

One thing I noticed now for the first time is the "reading order". This is probably really important for us, isn't it? When marking something as "table", it often seems to move it down to the bottom of the reading order, but you can move it back up again in "layout".

Also, I did another experiment on page 14: I tagged the table as a paragraph here and tried to use tabstops between the elements, hoping it would get them to align properly. The results will probably be disastrous though, but maybe worth a try.
