### ISSUE TITLE
Unicode for musical alteration symbols / potential of virtual keyboard feature

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#22]
Can we all agree to use the unicode symbols ♭, ♯ and ♮ for musical alterations in texts, as opposed to the similar looking symbols "b" and "#" on the keyboard? (can be found here: https://www.compart.com/de/unicode/search?q=Notenschrift#characters) 

For example, I used them on Riemann, Ideen zu einer Lehre, p. 9.

Also, I really like the "virtual keyboards" feature in Transkribus. Maybe it would be nice if we could all import a set of common musical symbols into it?

**Comment by fabianmoss** [comment]
Yes, using the unicode characters here makes sense. Likewise for the natural sign and double accidentals.

**Comment by fabianmoss** [comment]
Add unicode characters to Virtual Keyboard in Transkribus
