### ISSUE TITLE
Editorial rule about how to transcribe ratios ("80:81" vs. "80 : 81")

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#24]
I'd like to establish a rule about how to represent mathematical ratios, which are commonly used to define musical intervals. Example from Hauptmann p. 23:

![image](https://user-images.githubusercontent.com/75686579/104509819-7fd05500-55ea-11eb-96e7-24192c7dd927.png)

The question here is: Should there be spaces around the ":", or not? 

So far, I have represented such ratios without spaces, in the spirit of the rule prescribing that we ignore spaces before punctuation (see the other colon after "verschiedenen"). But I am not sure about this at all. I suppose one could argue for "80 : 81" as well, since that is closer to what it looks like in this source.

**Comment by fabianmoss** [comment]
I did not think of this situation before. I would say the colon (":") is not a punctuation sign here but a mathematical operator and thus semantically different (but using the same symbol). So the rule we established for punctuation signs doesn't apply. 

Still, the question remains how to transcribe it. Ideally (probably), we would mark it up as a mathematical expression and type set it using LaTeX but then we would have to include ratios and other expressions in our labeling system which goes beyond what this project is about. 

Personally, I think that "80 : 81" is visually more appropriate than "80:81" but if we encode it as "80 : 81" it might get split up at the end of lines which would be bad. Is there an option to introduce "invisible binders" (like the tilde "~" in LaTeX used for non-breakable space: https://en.wikibooks.org/wiki/LaTeX/Special_Characters)?

If not, we should transcribe it as "80:81". Please record the decision in the Wiki.

**Comment by m-k94** [comment]
alright, I will add the following sentence now: 

"Ratios such as "80:81", often appearing as "80 : 81" in texts, should be represented without spaces around the ":" - at least until a way to use non-breakable spaces be discovered."
