### ISSUE TITLE
Suggestion for editorial rule - concerning punctuation after tagged/highlighted words

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#25]
I suggest to add the following to the wiki as an editorial rule:
"Punctuation after a highlighted unit should not be included in the textStyle tag, unless it is actually highlighted as well." (wording still a bit clumsy, maybe)

It might sound a little obvious, but it's important because unlike most programs, Transkribus (unlike Word, Chrome etc.) marks the entire string of connected characters when you double click on a work. Thus, if you briefly don't pay attention, it looks like this:

![image](https://user-images.githubusercontent.com/75686579/104738190-7c051580-5745-11eb-85a6-e7ee32ab393b.png)
(Riemann 1880, p. 7)

The period at the end of "1. Klänge." is actually bold, so that's fine. But the commas and semi-colons after the letter spaced have been marked accidentally (by me double clicking), and are not actually highlighted in the text.

Is that a good addition or does it not really matter? This will be relevant for content tags as well (person, musical_concept, etc.).

**Comment by fabianmoss** [comment]
Yes, this is important. Please add it to the guidelines (don't worry about the wording as long as it's clear what you mean)

**Comment by m-k94** [comment]
added.
