### ISSUE TITLE
Editorial rules - Should page numbers always contain a simple integer?

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#28]
The documents represent page-numbers in different ways. Sometimes, the page number has little lines around it, e. g.: 
![image](https://user-images.githubusercontent.com/75686579/105077861-6b2e0a00-5a8d-11eb-94e0-c26821994ac2.png)
(Hostinsky 1879)

In my opinion, this is just an aesthetic choice on part of the publisher. Should we agree to always just transcribe the actual number as a simple integer?

**Comment by m-k94** [comment]
I guess roman numerals are also fine, I just mean to omit things like these lines or periods.

**Comment by fabianmoss** [comment]
Yes, it is fine just to transcribe the Arabic, Roman, or other kinds of numbers without graphical elements --> Guidelines
