### ISSUE TITLE
Small text

### ISSUE THREAD

**Issue by adnilem** [DCMLab/ddd#3]
I am not sure how to transcribe the small upper text in Reimann 1880 p.37 line 4-9:
<img width="129" alt="Screenshot 2021-01-06 at 12 13 32" src="https://user-images.githubusercontent.com/43856420/103763317-ef0dde00-5019-11eb-8481-26314fe103be.png">

This is what I have so far: "_g7, aVII_"

**Comment by fabianmoss** [comment]
In this case, you can make the first letter (e.g. _g_ and _a_) italic with the menu below the transcription window. Then, you can mark the 7 and the VII as superscript, using the "$x^2$ button also in this menu.

**Comment by adnilem** [comment]
Ok, thank you!
