### ISSUE TITLE
How to segment this? Paragraph with sort of "list" of formulas embedded

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#31]
![image](https://user-images.githubusercontent.com/75686579/105408513-5ab59500-5c2f-11eb-8397-f9352534afd2.png)

This page has lists with little formulas for musical intervals. Similar things come up frequently in this document too.

We should clarify how we want to segment and label this. In a way, it's all one paragraph. But the formulas are separated by indentation. (the second one actually even more than the first, although I'm not sure if that matters.) Also, are the list-elements themselves text or "math"?

I hope I'm not repeating myself too much with these issues. It's essentially another case of what I would call "embedded formatting". Like issue #20 , I'd like to somehow be able to specify if it's a different element _within_ a paragraph, or _between_ two paragraphs.

**Comment by fabianmoss** [comment]
This should be transcribed as a list indeed, with embedded "musical formulas". Is it possible to have lists in Transkribus? The musical expressions in the list items should be tagged and later encoded using LaTeX.

**Comment by m-k94** [comment]
I am not aware of lists in Transkribus. I suppose we could create a tag for that, though?
