### ISSUE TITLE
Somewhat messy baselines when dealing with fractions - Is it a problem at all?

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#32]
Not a big problem, but this happens so much in the Naumann text I'm working on that I felt compelled to make an issue.

Basically, automatic line recognition is slightly confused when fractions are used in the text. This is unsurprising, as they go below and above the text's baseline. My general approach when fixing line segmentation is to merge all recognized lines that relate to the same actual line. But in these cases it leads to some messiness, as line fragments are recognized above each other, leading to something like this:

![image](https://user-images.githubusercontent.com/75686579/105534577-fdcce400-5ced-11eb-9df9-38200282d3ed.png)
(p. 30)

I'm just wondering if there is any reason to tidy these kinds of lines up? The automatic transcription will likely be a completely wrong at these spots anyway, so I tend to think it's okay.

**Comment by fabianmoss** [comment]
This should be only one line of text. The complex in-line ratios should be tagged so that we can transcribe them correctly later using LaTeX.

**Comment by m-k94** [comment]
Just to clarify: it currently is one line of text, the line just behaves in a rather strange way, first going to the bottom part of the fraction and then the top.

**Comment by fabianmoss** [comment]
Ah right. I didn't see that. Then it doesn't really matter but the line could be simplified if that doesn't take too much time. It is not a big issue since we don't want to link the text to locations on the image (we only need that to extract musical examples).

**Comment by m-k94** [comment]
Alright, that's all I wanted to know. Thanks! I assumed it wouldn't be a problem, just wanted to make sure since it happens frequently in this text.
