### ISSUE TITLE
Idea: divide "paragraph" into three/four different structural tags (starting, complete, ending)

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#33]
If I simply mark all paragraphs as "paragraph" (Transkribus default), I cannot see how we are later going to be able to distinguish between two scenarios:

1. A paragraph ends at the bottom of a page and a new paragraph start on the next one.
2. A paragraph is begins on one page and is _continued_ on the next.

As far as I understand it, our exports would currently, in all cases, imply 1. to be the case. Given our goal to represent not the individual pages, but the structure of the text itself, this feels unsatisfactory to me.

Therefore, I propose that we create different structural tags for paragraphs (and probably for tables, graphics and musical examples as well), that contain information about whether or not the unit is fully enclosed in the region as marked, or if it is needs to be linked to another region (possibly on a different page) to be complete. You could have the following markups:

1. Paragraph started on the current page, is continued/ending on the next one. [e.g. "Paragraph_starting"]
2. Paragraph is complete. [e.g. "Paragraph_complete"]
3. Paragraph started on the previous page, is ending on the current one. [e.g. "Paragraph_ending"]
4. when the paragraph in neither starting nor ending on the current page. <- not sure if this is needed often, but it's logical. 

Furthermore, I think this could also be useful to deal with the problem of paragraphs continuing around examples/graphics. (issue #20)

You could have:
_Paragraph_starting_
_Music + floating_
_Paragraph_ending_ 
on the same page, and then we could understand from the exported data what the underlying structure actually is, while also keeping the information about the graphic's exact place in the reading order!

What do you think?

**Comment by fabianmoss** [comment]
Good observation. Since it is possible to have multiple tags on structural elements, it is sufficient to have a tag "continued" that is applied to all but the last part of a separated element, e.g.

* paragraph + continued
* paragraph + continued
* musical example
* paragraph + continued
* paragraph

It is clear that we have only one paragraph here, separated by page breaks and interrupted by a musical example.

**Comment by m-k94** [comment]
Great point, that is a much simpler way to deal with this indeed! Now the question is how to make that work on a technical level.

In fact, I had created a "continued" tag even before asking this question, and it works great in conjunction with tables/graphics etc, since we can set "Selected element type" to "Graphic", for example, and Structure type to "continued".

![image](https://user-images.githubusercontent.com/75686579/105889966-0a637c00-600f-11eb-9156-ea417872156d.png)

However, "paragraph" is itself defined as a structure type. (element type being "TextRegion"). So as of now, I don't see how the continued tag is compatible with the paragraph tag. I am probably missing something, but it seems to me that structure type tags are mutually exclusive.

If that is true, do we want to create two "paragraph" tags on the structure type level, in the style that already exists for "footnote" and "footnote-continued"? Music/graphics/tables could be slightly different I suppose, with a structure type being simply "continued" as described above. In that case, it would however also "take away" the structure type spot.
