### ISSUE TITLE
Musical examples (or graphics) in footnotes (Naumann)

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#34]
![image](https://user-images.githubusercontent.com/75686579/105641422-2a1a6900-5e84-11eb-90a3-53dd8d51d084.png)

Here we have a footnotes that contains a musical example. 

My first idea is to mark it as "music" and "footnote". It makes sense, but maybe we should consider adding a new option? As you can see from the screenshot, I gave it:
_text + footnote 
music + footnote
text + footnote_   (something like footnote_continued might also be an option, but we'd have to agree on how to use it, see also issue #33)

This puts everything in the "footnote" realm, but it's hard to represent the actual structure of such more complex footnotes using Transkribus default tags. Until now, I have understood "footnote" to always to the entire note. However, in this case it might be crucial to understand that it's not in fact three different footnotes, but three regions belonging to one.

**Comment by fabianmoss** [comment]
Footnote text is not different from "normal" text, it will be just displayed differently. This means we can use the splitting procedure ("continued") mentioned in issue #33.
