### ISSUE TITLE
When to use "floating" for musical examples/graphics, and what to use instead

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#36]
This is perhaps one of the more embarrassing questions, but I have to ask it sooner rather than later. I am not quite sure what exactly "floating" means and whether I am using it correctly. Due to how understood it in our initial meeting, I have been using it in almost all cases where a musical or a graphic shows up outside of the text, either in a separate paragraph or on the side with the text flowing around it.

What would help me is to know what exactly the opposite of floating would be. In our meeting, I have understood it to be in opposition to being "in line", is that correct? 

Is that generally correct? Within that understanding, I am not sure how I should tag images that are in line with the text, however. (e. g. the example in issue #29)

**Comment by fabianmoss** [comment]
Let's discuss this later this afternoon
