### ISSUE TITLE
Strikethrough 

### ISSUE THREAD

**Issue by adnilem** [DCMLab/ddd#4]
There are some strikethrough letters in Reimann 1880 p.37 line 4-11:
<img width="128" alt="Screenshot 2021-01-06 at 12 24 34" src="https://user-images.githubusercontent.com/43856420/103763619-63e11800-501a-11eb-9588-4dfa8707edd9.png">
Is the backslash important for the meaning or can normal ~~strikethrough~~ be used?

**Comment by fabianmoss** [comment]
This is a good question. I am not quite sure for now. I suggest that you use the normal ~~strikethrough~~. We will discuss a way to extract this after the break.

**Comment by fabianmoss** [comment]
Decision: We mark those expressions up with a specific tag (to be determined), and later use LaTeX to encode them. For the given example, this would be:

`$\bcancel{g}^{\text{7}}$, $\bcancel{a}^{\text{VII}}$`

Unfortunately, this doesn't render here, but I'll put it in the Wiki where it will be shown appropriately.

**Comment by fabianmoss** [comment]
Added to Wiki.
