### ISSUE TITLE
Distinguishing between music and graphic - metric illustrations using note-values

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#43]
![image](https://user-images.githubusercontent.com/75686579/107160886-4eed0100-6999-11eb-9862-b037e114716f.png)

Hauptmann frequently uses some notes with accents to represent ideas about rhythm, stress patterns etc.. I started to wonder whether to tag them as music or as a graphic. I suppose it's still music without a 5-line staff but I thought I'd ask to be sure.

**Comment by fabianmoss** [comment]
Yes, this is still music, even if we don't have note lines (this should occur frequently in the meter chapters, right)?
