### ISSUE TITLE
Theoretical illustrations using letters for notes, also headers within graphics

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#5]
Riemann 1880 on page 63 uses two short graphics to illustrate a point. They each have a heading associated with them. (see image attached)
![Graph Issue](https://user-images.githubusercontent.com/75686579/103764907-9ee44b00-501c-11eb-986d-170e597afe3e.png)

Though consisting mainly of text, such illustrations don't make any sense without the relationships indicated by the lines around them, which cannot be represented in plain text: "aaa) c a = d . f . a . c . e . g . " captures more of the visible elements but does not really have any meaning to it. Should I therefore better tag such elements as "graphics"?

A second question is whether or not to segment it so as to separate the headings. I have done so currently, tagging the lines starting with 26) and 27) as headers. But another possible interpretation would be to simply treat the entire block as a single graphic, with the headers being part of said graphic. My reasoning was that maybe it is best to keep text where it can be meaningfully transcribed.

This is probably a rather common scenario in this text-type!

**Comment by fabianmoss** [comment]
For the first case, I agree that we should not treat them as regular text. Second, the numbering on these pages is quite confusing to me. If you compare it to page 62 it becomes even a bit more complicated, where we have inline images that are not floats. Let's discuss this issue after the break.

**Comment by fabianmoss** [comment]
Actually, after our discussion, I think it is better to mark it up as "musical symbol" or something and then edit it as LaTeX afterwards.

**Comment by fabianmoss** [comment]
Added to Wiki.

**Comment by fabianmoss** [comment]
Added to Wiki.
