### ISSUE TITLE
Hauptmann - Time Signatures as fractions - $$MATH ?

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#55]
![image](https://user-images.githubusercontent.com/75686579/111871629-7e752d00-898b-11eb-9e35-184aa363e00a.png)

In Hauptmann's Metrik Chapter, he sometimes refers to time signatures with such consensed symbols as in the screenshot.

My first Idea was to use unicode. As the attempted transcription shows, there are some symbols for fractions. Unfortunately, there are none for musically common relations like 2/4, or 4/4. 

So for now, I am using $$MATH in these cases. But that also feels a bit silly, since it's literally just a symbol. The alternative could be to write them like "4/4", I suppose.

**Comment by m-k94** [comment]
I just found this tool: https://qaz.wtf/u/fraction.cgi?text=4%2F4 for converting fractions into unicode that looks a lot like the one in the text: ⁴⁄₄ .

would that be a solution? or should I continue writing $$MATH every time this comes up?

**Comment by fabianmoss** [comment]
In the case of time signatures, we can use the unicode fractions. For frequencies etc. we should use $$MATH

**Comment by m-k94** [comment]
Okay, I can replace all time signatures with the fractions as generated by that tool I linked.

What do you mean with frequencies? I hope you don't mean 1:2 type frequency ratios, because these I have consistently transcribed in accordance to issue #24

**Comment by fabianmoss** [comment]
I didn't mean any specific instance. Sorry that was not clear. I merely meant that for other fractions and more complex ones than the time signatures we can use the $$MATH placeholder.

**Comment by m-k94** [comment]
okay, for now I replaced only the time signatures and wrote a note in guidelines. 

Similar fractions in inverval context are still $$MATH for now.
