### ISSUE TITLE
spondeische / spondeïsche

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#57]
Very simple issue here: 

![image](https://user-images.githubusercontent.com/75686579/112145279-7232df00-8bda-11eb-90eb-c8b47d0b933f.png)

On the word "spondeische", Hauptmann appears to intentionally use a double dotted i, that we know today mostly from the word "naïve", 

I assume this should be transcriped with that special letter, correct?

In the first instances I wasn't sure if this was intentional, so the status quo is that it's consistently written with a normal "i". But I have a list of all pages were this happens and can change it if so desired!

**Comment by fabianmoss** [comment]
Yes exactly, please transcribe it with the two dots.

**Comment by m-k94** [comment]
Okay it's done - ï in all instaces. thanks for the response.
