### ISSUE TITLE
Oettingen: what is the word obscured by the ink dot?

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#69]
![image](https://user-images.githubusercontent.com/75686579/119223986-9c325000-bafc-11eb-9b19-c3e52c201242.png)

**Comment by fabianmoss** [comment]
I would guess it's "auch".

**Comment by fabianmoss** [comment]
Could also be "doch". In any case, it's not so important for our purpose. Please make a note in the guidelines so we can always refer back to this example. You can decide which word makes most sense to you.

**Comment by m-k94** [comment]
I went with "doch" for now, it made slightly more sense to me, but sounds a little odd as well. Not sure...
