### ISSUE TITLE
Oettingen - Some strange interruption of a sentence

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#70]
![image](https://user-images.githubusercontent.com/75686579/119269414-e0564b00-bbf7-11eb-957d-fe203ebb3f4d.png)

something isn't right here. The word "Verwandt-" isn't continued, instead a different sentence starts. What to do about this?

**Comment by fabianmoss** [comment]
That is strange indeed. It appears that this is an error in the print but I could not find a list of errata or a different edition. 
My suggestion is to transcribe the word in full "Verwandtschaft" and conclude the sentence there:
"Die Schwierigkeit derselben liegt, an der meist schwieriger aufzufassenden Verwandtschaft." (The comma is also weird but let's leave it.)

**Comment by m-k94** [comment]
okay I did just that, thanks!
