### ISSUE TITLE
Riemann - Sentence finished in handwritten pencil note -> to transcribe or not

### ISSUE THREAD

**Issue by m-k94** [DCMLab/ddd#71]
![image](https://user-images.githubusercontent.com/75686579/120884437-900dbe80-c5e3-11eb-8109-3c026acf96d9.png)

The printed sentence at the end of this paragraph ends with a comma, so it looks incomplete. But it's not clear if the handwritten part is an authentic part added from some other source.

I think it reads "ergeben also Doppelklang".

So far I have changed the comma to a full stop and neglected the handwritten bit.

**Comment by fabianmoss** [comment]
Yes, that was the right decision. I checked it in the book, and the comma was also made manually with a pencil (although it looks as if it could have been printed in the scan). So we can safely ignore what follows the period.
