### ISSUE TITLE
No spaces in between paragraphs

### ISSUE THREAD

**Issue by adnilem** [DCMLab/ddd#9]
The texts from Weitzmann (1860 and 1961) are pretty dense as there is no space in between paragraphs:
<img width="480" alt="Screenshot 2021-01-07 at 17 39 28" src="https://user-images.githubusercontent.com/43856420/103919075-e8fa2900-510f-11eb-8480-af6cd90f318c.png">
Here is a page with a musical example but some pages are only a block of text. 
I though about splitting the paragraphs in different TextRegions, but is it useful ?

**Comment by m-k94** [comment]
Hm, I would surely do it. The space left at the beginning of the line clearly indicates that it's a new paragraph.

I did it like that on my example page yesterday and it did not get criticized nor mentioned. Maybe I should have brought it up, but to me it seemed quite clear that some sort of "break" must be created between paragraphs, regardless of layout choices. Let's see what the others think.

**Comment by fabianmoss** [comment]
No you are right, these are new paragraphs as indicated by the indent at the beginning of the line. Normally, paragraphs indicate thematically somewhat closed units. It is not necessary that they are separated by a vertical space. So, in this and similar cases, please separate them into different TextRegions and mark each of them up as "paragraphs".

As a little practice, I added you @adnilem as Assignee for this issue. Please add this decision to [Editorial decisions](https://github.com/DCMLab/ddd/wiki/Editorial-decisions) and close this issue afterwards.
